language: go

go:
  - 1.15

install:
  -  # Do nothing. This is needed to prevent default install action

script:
  - cd api/
  - go get github.com/gorilla/mux
  - go get github.com/joho/godotenv
  - go test ./...
